### ISSUE TITLE
Add support for matrix-puppet-server

### ISSUE THREAD

**Issue by MurzNN** [matrix-hacks/matrix-puppet-hangouts#11]
Seems `matrix-puppet-server` already in working state, at least it works for me with `matrix-puppet-skype`.
But seems external bridge code must be adapted from `matrix-puppet-bridge` to `matrix-puppet-server`, here is branch of Skype bridge for puppet server: https://github.com/matrix-hacks/matrix-puppet-skype/tree/develop
Can you port your bridge too?

**Comment by bobpaul** [comment]
`matrix-puppet-server` looks dead, while `matrix-puppet-bridge` is still under development. The README for `-server` doesn't explain why it's an improvement over `-bridge`.

**Comment by AndrewJDR** [comment]
I would say the spiritual successor to the (now defunct) matrix-puppet-server project is the mx-puppet-bridge project from  @Sorunome 

You can look over its feature list here - https://github.com/Sorunome/mx-puppet-bridge
One major feature it has over matrix-puppet-bridge is:
> Multi-account (many matrix users can start many remote links)

This was also the case for the matrix-puppet-server project. mx-puppet-bridge and matrix-puppet-server were/are typescript based from the beginning, as well, whereas matrix-puppet-bridge is plain js.

I'd encourage anyone that wants multi-account features, typescript, or some of the architectural differences to contribute to the mx-puppet-bridge project, as I don't really see many of those happening anytime soon with matrix-puppet-bridge unless somebody ambitious with the time to spare comes along to do the work...

For example, if you'd really like to see hangouts support with mx-puppet-bridge, feel free to port this project over to it. One thing I'll mention -- the future of the hangouts protocol in general is very uncertain, with a lot of reports of Google planning to kill it or transition it to some kind of "business only" type service. Therefore you might want to think twice before investing much time into hangouts as a protocol, at this point.

That said, if you decide to take it on, you have two main paths:
hangups-js - a js-native port of hangups - https://github.com/yakyak/hangupsjs
hangups - https://github.com/tdryer/hangups - this is a python-based hangouts client protocol implementation. this is what this project uses through a cockamamie js <-> python pipes-based IPC scheme. This has been quite reliable, whereas I found that hangupsjs had some reliability issues, silently dropping messages to google voice contacts in particular. Maybe hangupsjs has improved since then...

**Comment by AndrewJDR** [comment]
Side note, I consider this a completely separate effort (i.e. it would mean creating a new project that is set up to work with mx-puppet-bridge), so i'll close this.
